import { useState } from 'react';
import { GestureResponderEvent, Pressable, Text, TextInput, View } from 'react-native';
import { RotateCcw, X } from 'lucide-react-native';
import { useThemeColors } from '@/src/hooks/use-theme-colors';
import { typography } from '@/src/theme/typography';
import { radius } from '@/src/theme/radius';

export interface BodyMapPoint { view: 'FRONT' | 'BACK'; x: number; y: number; label: string; note: string }
const region = (_x: number, y: number) => y < 18 ? 'Head / neck' : y < 42 ? 'Upper body' : y < 65 ? 'Lower body' : 'Leg / foot';
export function BodyMapSelector({ value, onChange }: { value: BodyMapPoint[]; onChange: (points: BodyMapPoint[]) => void }) {
  const colors = useThemeColors(); const [view,setView]=useState<'FRONT'|'BACK'>('FRONT'); const [size,setSize]=useState({width:1,height:1});
  const add=(event:GestureResponderEvent)=>{ const x=Math.round(event.nativeEvent.locationX/size.width*100); const y=Math.round(event.nativeEvent.locationY/size.height*100); onChange([...value,{view,x,y,label:region(x,y),note:''}]); };
  return <View style={{ marginTop: 12 }}><View style={{ flexDirection:'row',gap:8,marginBottom:8 }}>{(['FRONT','BACK'] as const).map(item=><Pressable key={item} onPress={()=>setView(item)} style={{paddingHorizontal:14,paddingVertical:8,borderRadius:radius.full,backgroundColor:view===item?colors.primary:colors.surface,borderWidth:1,borderColor:view===item?colors.primary:colors.border}}><Text style={{...typography.label,color:view===item?'white':colors.secondary}}>{item==='FRONT'?'Front':'Back'}</Text></Pressable>)}</View><Pressable accessibilityLabel={`Select a location on the ${view.toLowerCase()} body map`} onLayout={e=>setSize(e.nativeEvent.layout)} onPress={add} style={{height:300,borderRadius:radius.lg,borderWidth:1,borderColor:colors.border,backgroundColor:colors.surface,alignItems:'center',justifyContent:'center',overflow:'hidden'}}><View style={{width:46,height:46,borderRadius:23,borderWidth:2,borderColor:colors.secondary,marginBottom:5}}/><View style={{width:92,height:112,borderRadius:38,borderWidth:2,borderColor:colors.secondary}}/><View style={{flexDirection:'row',gap:18,marginTop:5}}><View style={{width:28,height:105,borderRadius:14,borderWidth:2,borderColor:colors.secondary}}/><View style={{width:28,height:105,borderRadius:14,borderWidth:2,borderColor:colors.secondary}}/></View>{value.filter(p=>p.view===view).map((point,index)=><View key={`${point.x}-${point.y}-${index}`} pointerEvents="none" style={{position:'absolute',left:`${point.x}%`,top:`${point.y}%`,width:18,height:18,borderRadius:9,marginLeft:-9,marginTop:-9,backgroundColor:colors.status.critical,borderWidth:2,borderColor:'white'}}/>)}</Pressable><Text style={{...typography.caption,color:colors.secondary,marginTop:6}}>Tap the body outline to mark each observed area. Confirm the description below.</Text>{value.map((point,index)=><View key={`${point.view}-${index}`} style={{marginTop:10,padding:10,borderWidth:1,borderColor:colors.border,borderRadius:radius.md}}><View style={{flexDirection:'row',alignItems:'center',gap:8}}><Text style={{...typography.label,color:colors.text,flex:1}}>{point.view.toLowerCase()} · {point.label}</Text><Pressable onPress={()=>onChange(value.filter((_,i)=>i!==index))}><X size={18} color={colors.status.critical}/></Pressable></View><TextInput value={point.note} onChangeText={note=>onChange(value.map((item,i)=>i===index?{...item,note}:item))} placeholder="What was observed?" placeholderTextColor={colors.secondary} style={{...typography.body,color:colors.text,marginTop:6}}/></View>)}{value.length?<Pressable onPress={()=>onChange([])} style={{flexDirection:'row',gap:6,alignItems:'center',marginTop:10}}><RotateCcw size={16} color={colors.secondary}/><Text style={{...typography.label,color:colors.secondary}}>Clear body map</Text></Pressable>:null}</View>;
}
