import { useCallback, useState } from 'react';
import { Alert, Pressable, Text, View } from 'react-native';
import { Stack, useFocusEffect } from 'expo-router';
import { CloudUpload, RefreshCw, Trash2 } from 'lucide-react-native';
import { ScreenContainer } from '@/src/components/ui/ScreenContainer';
import { Card } from '@/src/components/ui/Card';
import { EmptyState } from '@/src/components/ui/EmptyState';
import { useAuthStore } from '@/src/stores/auth-store';
import { pendingOfflineMutations, removeOfflineMutation, resetOfflineMutationAttempts, type OfflineMutation } from '@/src/offline/offline-db';
import { describeOfflineMutation, flushOfflineQueue, mutationNeedsAttention } from '@/src/offline/offline-sync';
import { useThemeColors } from '@/src/hooks/use-theme-colors';
import { typography } from '@/src/theme/typography';
export default function SyncStatusScreen(){const colors=useThemeColors();const ownerId=useAuthStore(s=>s.user?.id);const[items,setItems]=useState<OfflineMutation[]|null>(null);const[syncing,setSyncing]=useState(false);const reload=useCallback(async()=>setItems(ownerId?await pendingOfflineMutations(ownerId):[]),[ownerId]);useFocusEffect(useCallback(()=>{void reload()},[reload]));const sync=async()=>{if(!ownerId)return;setSyncing(true);await flushOfflineQueue(ownerId);setSyncing(false);await reload()};const discard=(item:OfflineMutation)=>Alert.alert('Discard saved update?',`This ${describeOfflineMutation(item).toLowerCase()} has not reached the server. Discarding permanently removes it from this device.`,[{text:'Keep',style:'cancel'},{text:'Discard',style:'destructive',onPress:async()=>{await removeOfflineMutation(item.id);await reload()}}]);return <><Stack.Screen options={{headerShown:true,title:'Sync status'}}/><ScreenContainer><Card style={{marginBottom:14}}><Text style={{...typography.bodyMedium,color:colors.text}}>{items?.length?`${items.length} update${items.length===1?'':'s'} waiting to send`:'Care records on this device'}</Text>{items?.length?<Pressable disabled={syncing} onPress={()=>void sync()} style={{marginTop:12,padding:12,borderRadius:10,backgroundColor:colors.primary}}><Text style={{...typography.bodyMedium,color:'white',textAlign:'center'}}>{syncing?'Syncing…':'Sync now'}</Text></Pressable>:null}</Card>{items&&!items.length?<EmptyState icon={CloudUpload} title="All synced" description="Offline care records appear here until they reach the server."/>:<View style={{gap:10}}>{items?.map(item=><Card key={item.id}><Text style={{...typography.bodyMedium,color:colors.text}}>{describeOfflineMutation(item)}</Text><Text style={{...typography.caption,color:mutationNeedsAttention(item)?colors.status.critical:colors.secondary,marginTop:4}}>{mutationNeedsAttention(item)?item.lastError||'Needs attention':`Saved ${new Date(item.createdAt).toLocaleString()}`}</Text><View style={{flexDirection:'row',gap:10,marginTop:10}}><Pressable onPress={async()=>{await resetOfflineMutationAttempts(item.id);await sync()}} style={{padding:10}}><RefreshCw size={19} color={colors.primary}/></Pressable><Pressable onPress={()=>discard(item)} style={{padding:10}}><Trash2 size={19} color={colors.status.critical}/></Pressable></View></Card>)}</View>}</ScreenContainer></>}
